# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'music.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\x12\x05music\"\x07\n\x05\x45mpty\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"5\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"&\n\x08UserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.music.User\"&\n\x08SongList\x12\x1a\n\x05songs\x18\x01 \x03(\x0b\x32\x0b.music.Song\"2\n\x0cPlaylistList\x12\"\n\tplaylists\x18\x01 \x03(\x0b\x32\x0f.music.Playlist2\x9b\x02\n\x0cMusicService\x12+\n\x08GetUsers\x12\x0c.music.Empty\x1a\x0f.music.UserList\"\x00\x12+\n\x08GetSongs\x12\x0c.music.Empty\x1a\x0f.music.SongList\"\x00\x12;\n\x10GetUserPlaylists\x12\x10.music.IdRequest\x1a\x13.music.PlaylistList\"\x00\x12\x37\n\x10GetPlaylistSongs\x12\x10.music.IdRequest\x1a\x0f.music.SongList\"\x00\x12;\n\x10GetSongPlaylists\x12\x10.music.IdRequest\x1a\x13.music.PlaylistList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_IDREQUEST']._serialized_start=31
  _globals['_IDREQUEST']._serialized_end=54
  _globals['_USER']._serialized_start=56
  _globals['_USER']._serialized_end=101
  _globals['_SONG']._serialized_start=103
  _globals['_SONG']._serialized_end=151
  _globals['_PLAYLIST']._serialized_start=153
  _globals['_PLAYLIST']._serialized_end=206
  _globals['_USERLIST']._serialized_start=208
  _globals['_USERLIST']._serialized_end=246
  _globals['_SONGLIST']._serialized_start=248
  _globals['_SONGLIST']._serialized_end=286
  _globals['_PLAYLISTLIST']._serialized_start=288
  _globals['_PLAYLISTLIST']._serialized_end=338
  _globals['_MUSICSERVICE']._serialized_start=341
  _globals['_MUSICSERVICE']._serialized_end=624
# @@protoc_insertion_point(module_scope)
